version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sistemas
    ports:
      - "5432:5432"

  phppgadmin:
    image: dockage/phppgadmin
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DEFAULTDB: sistemas
    ports:
      - "80:80"
    depends_on:
      - postgres

  fill_users:
    image: postgres
    restart: "no"
    depends_on:
      - postgres
    environment:
      PGPASSWORD: 123456
      PGDATABASE: sistemas
      PGUSER: postgres
      PGHOST: postgres
    command: bash -c "psql -c 'INSERT INTO usuarios (nickname, password) VALUES ('user1', 'password1'), ('user2', 'password2'), ('user3', 'password3'), ('user4', 'password4'), ('user5', 'password5')'"

